"""Adding endpoints

Revision ID: be867556e39c
Revises: b6aec9715b77
Create Date: 2024-01-14 23:58:01.093237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be867556e39c'
down_revision = 'b6aec9715b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
